spring:
  config:
    import: optional:dependencies.properties
  application:
    name: autometrics-hello-app

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

app:
  version: 1.0.0
