global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'autometrics-otel'
    metrics_path: /actuator/prometheus
    scrape_interval: 5s
    static_configs:
      - targets: [ 'autometrics-demo-app:8080' ]